version: "3"

services:

  unsecure-web:
    build:
      context: ./src/unsecure
      dockerfile: caddy.dockerfile
    volumes:
      - ./src/unsecure/src:/var/www/html
      - unsecure-uploads:/var/www/html/uploads
    ports:
      - 8080:80

  unsecure-php:
    build:
      context: ./src/unsecure
    volumes:
      - ./src/unsecure/src:/var/www/html
      - unsecure-uploads:/var/www/html/uploads
    environment:
      - DB_HOST=db
      - DB_NAME=exam
      - DB_USERNAME=exam
      - DB_PASSWORD=eIggr3T18BNkLZ17

  secure-web:
    build:
      context: ./src/secure
      dockerfile: caddy.dockerfile
    volumes:
      - ./src/secure/src:/var/www/html
      - secure-uploads:/var/www/uploads
    ports:
      - 8081:80

  secure-php:
    build:
      context: ./src/secure
    volumes:
      - ./src/secure/src:/var/www/html
      - secure-uploads:/var/www/uploads
    environment:
      - DB_HOST=db
      - DB_NAME=exam
      - DB_USERNAME=exam
      - DB_PASSWORD=eIggr3T18BNkLZ17

  better-web:
    build:
      context: ./src/better
      dockerfile: caddy.dockerfile
    volumes:
      - ./src/better/src:/var/www/html
      - better-uploads:/var/www/uploads
    ports:
      - 8082:80

  better-php:
    build:
      context: ./src/better
    volumes:
      - ./src/better/src:/var/www/html
      - better-uploads:/var/www/uploads
    environment:
      - DB_HOST=db
      - DB_NAME=exam
      - DB_USERNAME=exam
      - DB_PASSWORD=eIggr3T18BNkLZ17
      - DB_TEST_NAME=exam_test
      - DB_TEST_USERNAME=exam_test
      - DB_TEST_PASSWORD=TwK0kdEUy7xff3Jv

  laravel-web:
    build:
      context: ./src/laravel/caddy
    ports:
      - 8083:80

  laravel-php:
    build:
      context: ./src/laravel
    volumes:
      - ./src/laravel/src:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=exam
      - DB_USERNAME=exam
      - DB_PASSWORD=eIggr3T18BNkLZ17

  db:
    image: mariadb:10.5.9-focal
    environment:
      - MYSQL_ROOT_PASSWORD=cpuSUW49oS9TNIzB
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql

volumes:
  unsecure-uploads:
  secure-uploads:
  better-uploads:
